apiVersion: v1
kind: Pod
metadata:
  name: nginx-log
  labels:
    app: nginx-log

spec:
  containers:

  - name: logrotate
    image: horiz0n/logrotate:latest
    volumeMounts:
    - name: logs
      mountPath: /var/log

  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: logs
      mountPath: /var/log/nginx
      subPath: nginx

  volumes:
  - name: logs
    emptyDir: {}
